-- V3__datos_semilla.sql
-- Datos semilla realistas para demostrar el CRUD paginado/filtrado de Mascota.
-- No usa IDs explicitos: los duenios se insertan primero y las mascotas los
-- referencian por email via subconsulta, respetando la secuencia BIGSERIAL
-- y la FK fk_mascotas_duenio sin necesidad de setval().

INSERT INTO usuarios (nombre, email, password_hash, rol) VALUES
('María Fernanda Cedeño', 'maria.cedeno@correo.ec', '$2a$12$gakrr/U11GN6OWm6/3qJTetHIKDv09lUlG5TOnxYzfGc9mT6vJY8m', 'ROLE_DUENO'),
('Carlos Andrés Zambrano', 'carlos.zambrano@correo.ec', '$2a$12$gakrr/U11GN6OWm6/3qJTetHIKDv09lUlG5TOnxYzfGc9mT6vJY8m', 'ROLE_DUENO'),
('Lucía Morales Pincay', 'lucia.morales@correo.ec', '$2a$12$gakrr/U11GN6OWm6/3qJTetHIKDv09lUlG5TOnxYzfGc9mT6vJY8m', 'ROLE_DUENO'),
('José Luis Macías', 'jose.macias@correo.ec', '$2a$12$gakrr/U11GN6OWm6/3qJTetHIKDv09lUlG5TOnxYzfGc9mT6vJY8m', 'ROLE_DUENO'),
('Andrea Vera Loor', 'andrea.vera@correo.ec', '$2a$12$gakrr/U11GN6OWm6/3qJTetHIKDv09lUlG5TOnxYzfGc9mT6vJY8m', 'ROLE_DUENO'),
('Diego Cevallos Zambrano', 'diego.cevallos@correo.ec', '$2a$12$gakrr/U11GN6OWm6/3qJTetHIKDv09lUlG5TOnxYzfGc9mT6vJY8m', 'ROLE_DUENO'),
('Paola Intriago Chávez', 'paola.intriago@correo.ec', '$2a$12$gakrr/U11GN6OWm6/3qJTetHIKDv09lUlG5TOnxYzfGc9mT6vJY8m', 'ROLE_DUENO'),
('Fernando Solórzano', 'fernando.solorzano@correo.ec', '$2a$12$gakrr/U11GN6OWm6/3qJTetHIKDv09lUlG5TOnxYzfGc9mT6vJY8m', 'ROLE_DUENO'),
('Gabriela Pincay Reyes', 'gabriela.pincay@correo.ec', '$2a$12$gakrr/U11GN6OWm6/3qJTetHIKDv09lUlG5TOnxYzfGc9mT6vJY8m', 'ROLE_DUENO'),
('Miguel Ángel Bravo', 'miguel.bravo@correo.ec', '$2a$12$gakrr/U11GN6OWm6/3qJTetHIKDv09lUlG5TOnxYzfGc9mT6vJY8m', 'ROLE_DUENO'),
('Daniela Moreira Alcívar', 'daniela.moreira@correo.ec', '$2a$12$gakrr/U11GN6OWm6/3qJTetHIKDv09lUlG5TOnxYzfGc9mT6vJY8m', 'ROLE_DUENO'),
('Ricardo Villamar', 'ricardo.villamar@correo.ec', '$2a$12$gakrr/U11GN6OWm6/3qJTetHIKDv09lUlG5TOnxYzfGc9mT6vJY8m', 'ROLE_DUENO'),
('Sofía Chávez Loor', 'sofia.chavez@correo.ec', '$2a$12$gakrr/U11GN6OWm6/3qJTetHIKDv09lUlG5TOnxYzfGc9mT6vJY8m', 'ROLE_DUENO'),
('Javier Alcívar Ponce', 'javier.alcivar@correo.ec', '$2a$12$gakrr/U11GN6OWm6/3qJTetHIKDv09lUlG5TOnxYzfGc9mT6vJY8m', 'ROLE_DUENO'),
('Valentina Loor Mera', 'valentina.loor@correo.ec', '$2a$12$gakrr/U11GN6OWm6/3qJTetHIKDv09lUlG5TOnxYzfGc9mT6vJY8m', 'ROLE_DUENO'),
('Esteban Ponce Bravo', 'esteban.ponce@correo.ec', '$2a$12$gakrr/U11GN6OWm6/3qJTetHIKDv09lUlG5TOnxYzfGc9mT6vJY8m', 'ROLE_DUENO'),
('Camila Reyes Sánchez', 'camila.reyes@correo.ec', '$2a$12$gakrr/U11GN6OWm6/3qJTetHIKDv09lUlG5TOnxYzfGc9mT6vJY8m', 'ROLE_DUENO'),
('Alexander Mera Zambrano', 'alexander.mera@correo.ec', '$2a$12$gakrr/U11GN6OWm6/3qJTetHIKDv09lUlG5TOnxYzfGc9mT6vJY8m', 'ROLE_DUENO'),
('Natalia Sánchez Cedeño', 'natalia.sanchez@correo.ec', '$2a$12$gakrr/U11GN6OWm6/3qJTetHIKDv09lUlG5TOnxYzfGc9mT6vJY8m', 'ROLE_DUENO'),
('Bryan Zambrano Macías', 'bryan.zambrano@correo.ec', '$2a$12$gakrr/U11GN6OWm6/3qJTetHIKDv09lUlG5TOnxYzfGc9mT6vJY8m', 'ROLE_DUENO')
ON CONFLICT (email) DO NOTHING;

INSERT INTO mascotas (duenio_id, nombre, especie, raza, fecha_nacimiento)
SELECT u.id, v.nombre, v.especie, v.raza, v.fecha_nacimiento::date
FROM (VALUES
    ('maria.cedeno@correo.ec', 'Luna', 'Perro', 'Labrador', '2021-03-14'),
    ('maria.cedeno@correo.ec', 'Michi', 'Gato', 'Persa', '2022-07-02'),
    ('maria.cedeno@correo.ec', 'Coco', 'Ave', 'Canario', '2023-01-19'),
    ('carlos.zambrano@correo.ec', 'Rocky', 'Perro', 'Pastor Alemán', '2019-11-05'),
    ('carlos.zambrano@correo.ec', 'Bella', 'Gato', 'Siamés', '2020-05-22'),
    ('carlos.zambrano@correo.ec', 'Toby', 'Perro', 'Beagle', '2022-09-30'),
    ('lucia.morales@correo.ec', 'Nala', 'Gato', 'Angora', '2021-02-11'),
    ('lucia.morales@correo.ec', 'Simba', 'Gato', 'Maine Coon', '2020-08-17'),
    ('lucia.morales@correo.ec', 'Firulais', 'Perro', 'Mestizo', '2018-12-25'),
    ('jose.macias@correo.ec', 'Kira', 'Perro', 'Husky Siberiano', '2022-04-08'),
    ('jose.macias@correo.ec', 'Thor', 'Perro', 'Bulldog Francés', '2021-06-30'),
    ('jose.macias@correo.ec', 'Lola', 'Conejo', 'Holandés', '2023-03-15'),
    ('andrea.vera@correo.ec', 'Zeus', 'Perro', 'Pastor Alemán', '2019-01-27'),
    ('andrea.vera@correo.ec', 'Maya', 'Gato', 'Bengalí', '2022-10-10'),
    ('andrea.vera@correo.ec', 'Duke', 'Perro', 'Schnauzer', '2020-02-14'),
    ('diego.cevallos@correo.ec', 'Nina', 'Gato', 'Mestizo', '2021-09-09'),
    ('diego.cevallos@correo.ec', 'Rex', 'Perro', 'Labrador', '2018-07-04'),
    ('diego.cevallos@correo.ec', 'Sasha', 'Perro', 'Poodle', '2023-05-20'),
    ('paola.intriago@correo.ec', 'Bruno', 'Perro', 'Chihuahua', '2022-01-01'),
    ('paola.intriago@correo.ec', 'Mia', 'Gato', 'Siamés', '2021-11-11'),
    ('paola.intriago@correo.ec', 'Leo', 'Gato', 'Persa', '2020-03-03'),
    ('fernando.solorzano@correo.ec', 'Chispa', 'Perro', 'Mestizo', '2019-08-19'),
    ('fernando.solorzano@correo.ec', 'Canela', 'Perro', 'Beagle', '2022-12-24'),
    ('fernando.solorzano@correo.ec', 'Pelusa', 'Conejo', 'Cabeza de León', '2023-06-06'),
    ('gabriela.pincay@correo.ec', 'Manchas', 'Perro', 'Mestizo', '2020-10-01'),
    ('gabriela.pincay@correo.ec', 'Estrella', 'Gato', 'Angora', '2021-04-16'),
    ('gabriela.pincay@correo.ec', 'Sombra', 'Gato', 'Mestizo', '2018-09-23'),
    ('miguel.bravo@correo.ec', 'Copito', 'Conejo', 'Mestizo', '2022-02-28'),
    ('miguel.bravo@correo.ec', 'Rayo', 'Perro', 'Husky Siberiano', '2021-07-07'),
    ('miguel.bravo@correo.ec', 'Princesa', 'Perro', 'Poodle', '2020-01-13'),
    ('daniela.moreira@correo.ec', 'Tigre', 'Gato', 'Bengalí', '2019-05-05'),
    ('daniela.moreira@correo.ec', 'Blacky', 'Perro', 'Labrador', '2023-02-02'),
    ('daniela.moreira@correo.ec', 'Whisky', 'Gato', 'Maine Coon', '2022-06-18'),
    ('ricardo.villamar@correo.ec', 'Bombón', 'Perro', 'Chihuahua', '2021-12-12'),
    ('ricardo.villamar@correo.ec', 'Michi', 'Gato', 'Mestizo', '2020-11-29'),
    ('ricardo.villamar@correo.ec', 'Fiona', 'Perro', 'Golden Retriever', '2019-03-08'),
    ('sofia.chavez@correo.ec', 'Rambo', 'Perro', 'Bulldog Francés', '2022-08-08'),
    ('sofia.chavez@correo.ec', 'Dante', 'Perro', 'Pastor Alemán', '2021-01-21'),
    ('sofia.chavez@correo.ec', 'Nube', 'Gato', 'Persa', '2023-04-04'),
    ('javier.alcivar@correo.ec', 'Trueno', 'Perro', 'Husky Siberiano', '2020-06-15'),
    ('javier.alcivar@correo.ec', 'Perla', 'Gato', 'Siamés', '2019-10-10'),
    ('javier.alcivar@correo.ec', 'Tango', 'Perro', 'Beagle', '2022-03-27'),
    ('valentina.loor@correo.ec', 'Vainilla', 'Conejo', 'Holandés', '2021-05-30'),
    ('valentina.loor@correo.ec', 'Panda', 'Perro', 'Mestizo', '2023-07-01'),
    ('valentina.loor@correo.ec', 'Lucero', 'Ave', 'Periquito', '2020-04-12'),
    ('esteban.ponce@correo.ec', 'Simona', 'Gato', 'Mestizo', '2018-02-20'),
    ('esteban.ponce@correo.ec', 'Bigotes', 'Gato', 'Angora', '2022-11-05'),
    ('esteban.ponce@correo.ec', 'Poncho', 'Perro', 'Schnauzer', '2021-08-08'),
    ('camila.reyes@correo.ec', 'Wasabi', 'Perro', 'Shiba Inu', '2020-09-09'),
    ('camila.reyes@correo.ec', 'Frida', 'Gato', 'Persa', '2023-01-01'),
    ('camila.reyes@correo.ec', 'Otto', 'Perro', 'Bulldog Francés', '2019-06-06'),
    ('alexander.mera@correo.ec', 'Nano', 'Hámster', 'Sirio', '2023-09-15'),
    ('alexander.mera@correo.ec', 'Yoko', 'Gato', 'Mestizo', '2022-05-05'),
    ('alexander.mera@correo.ec', 'Kiko', 'Ave', 'Loro', '2021-10-20'),
    ('natalia.sanchez@correo.ec', 'Draco', 'Perro', 'Pastor Alemán', '2020-12-12'),
    ('natalia.sanchez@correo.ec', 'Freya', 'Gato', 'Maine Coon', '2019-04-04'),
    ('bryan.zambrano@correo.ec', 'Tortu', 'Tortuga', 'Terrestre', '2018-01-01'),
    ('bryan.zambrano@correo.ec', 'Kiara', 'Perro', 'Labrador', '2022-02-22')
) AS v(duenio_email, nombre, especie, raza, fecha_nacimiento)
JOIN usuarios u ON u.email = v.duenio_email;
